name: Convert Markdown files to HTML

on:
  push:
    branches:
      - main  # Adjust if you use a different default branch

permissions:
  contents: write  # Grants write permission to the GITHUB_TOKEN

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Install Latest Pandoc
        run: |
          PANDOC_VERSION=3.1.7
          wget https://github.com/jgm/pandoc/releases/download/$PANDOC_VERSION/pandoc-$PANDOC_VERSION-1-amd64.deb
          sudo dpkg -i pandoc-$PANDOC_VERSION-1-amd64.deb

      - name: Convert curriculum.md to curriculum/index.html with inline CSS
        run: |
          pandoc curriculum.md -o curriculum.html --standalone --embed-resources --css style.css --metadata title="Intro I Curriculum" --include-in-header=head.html --resource-path=. 
          
          # Ensure the curriculum directory exists
          mkdir -p curriculum
          # Copy curriculum.html into the curriculum directory
          cp curriculum.html curriculum/
          # Delete the existing index.html in the curriculum directory
          rm -f curriculum/index.html
          # Rename curriculum.html to index.html within the curriculum directory
          mv curriculum/curriculum.html curriculum/index.html

      - name: Convert index.md to index.html with inline CSS
        run: pandoc index.md -o index.html --standalone --embed-resources --css style.css --metadata title="701 Workshop Series" --include-in-header=head.html --resource-path=. 

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-generate HTML files from Markdown"
          file_pattern: |
            index.html
            curriculum/index.html
